receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318   # ← 原来是 localhost:4318
      grpc:
        endpoint: 0.0.0.0:4317   # ← 原来是 localhost:4317
processors:
  memory_limiter:
    check_interval: 5s
    limit_mib: 256
  batch:
    timeout: 2s
    send_batch_size: 512

exporters:
  otlphttp:
    endpoint: http://jaeger:4318
    compression: gzip
    timeout: 10s
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 10s
      max_elapsed_time: 0
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp, debug]
  telemetry:
    metrics:
      address: 0.0.0.0:8888
