# docker-compose.yml
services:
  db:
    image: postgres:14-alpine
    container_name: wms-du-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: wms
      POSTGRES_PASSWORD: wms
      POSTGRES_DB: wms
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wms -d wms"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg_data:
