"""Initial migration

Revision ID: 495074aac8bf
Revises:
Create Date: 2025-10-01 22:39:14.057006

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "495074aac8bf"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
