"""schema_drift_cleanup_20251207

Revision ID: 11fce062778b
Revises: 3bd0c5797f13
Create Date: 2025-12-07 18:20:29.884148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "11fce062778b"
down_revision: Union[str, Sequence[str], None] = "3bd0c5797f13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    def index_exists(table: str, name: str) -> bool:
        return (
            conn.execute(
                sa.text(
                    """
                    SELECT 1
                    FROM pg_indexes
                    WHERE schemaname = 'public'
                      AND tablename = :t
                      AND indexname = :n
                    """
                ),
                {"t": table, "n": name},
            ).scalar()
            is not None
        )

    # ### commands auto generated by Alembic - adjusted ###

    # batches
    op.alter_column(
        "batches",
        "supplier_lot",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.create_index(
        "ix_batches_item_wh_code",
        "batches",
        ["item_id", "warehouse_id", "batch_code"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_batches_item_wh_code",
        "batches",
        ["item_id", "warehouse_id", "batch_code"],
    )
    op.create_foreign_key(
        None, "batches", "warehouses", ["warehouse_id"], ["id"], ondelete="RESTRICT"
    )

    # event_error_log
    op.alter_column(
        "event_error_log",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )

    # event_store
    op.add_column(
        "event_store",
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "event_store",
        sa.Column("last_error", sa.Text(), nullable=True),
    )
    op.alter_column(
        "event_store",
        "topic",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        nullable=False,
    )
    op.alter_column(
        "event_store",
        "key",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "event_store",
        "payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=False,
    )
    op.alter_column(
        "event_store",
        "headers",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "event_store",
        "status",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.Text(),
        nullable=False,
    )
    op.alter_column(
        "event_store",
        "trace_id",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        nullable=True,
    )
    op.create_index(
        "ix_event_store_occurred",
        "event_store",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_event_store_status",
        "event_store",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_event_store_topic",
        "event_store",
        ["topic"],
        unique=False,
    )

    # inventory_movements
    op.alter_column(
        "inventory_movements",
        "item_sku",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    movement_enum = sa.Enum(
        "RECEIPT", "SHIPMENT", "TRANSFER", "ADJUSTMENT", name="movementtype"
    )
    op.alter_column(
        "inventory_movements",
        "movement_type",
        existing_type=sa.TEXT(),
        type_=movement_enum,
        existing_nullable=False,
        postgresql_using="movement_type::movementtype",
    )
    op.alter_column(
        "inventory_movements",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )

    # item_barcodes
    op.alter_column(
        "item_barcodes",
        "kind",
        existing_type=sa.TEXT(),
        comment="条码类型：EAN13 / UPC / INNER / CUSTOM ...",
        existing_nullable=False,
        existing_server_default=sa.text("'EAN13'::text"),
    )
    # 这个索引在某些库上已经存在，因此加一个存在性检查
    if not index_exists("item_barcodes", "uq_item_barcodes_barcode"):
        op.create_index(
            "uq_item_barcodes_barcode",
            "item_barcodes",
            ["barcode"],
            unique=True,
        )
    ix_item_id_name = op.f("ix_item_barcodes_item_id")
    if not index_exists("item_barcodes", ix_item_id_name):
        op.create_index(
            ix_item_id_name,
            "item_barcodes",
            ["item_id"],
            unique=False,
        )

    # items
    op.alter_column(
        "items",
        "weight_kg",
        existing_type=sa.NUMERIC(precision=10, scale=3),
        comment="单件净重（kg），用于运费预估，不含包材",
        existing_comment="单件净重（kg），用于运费预估（不含包材）",
        existing_nullable=True,
    )

    # locations
    op.create_index(
        "ix_locations_warehouse_id",
        "locations",
        ["warehouse_id"],
        unique=False,
    )
    op.create_index(
        "ix_locations_wh",
        "locations",
        ["warehouse_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "locations", "warehouses", ["warehouse_id"], ["id"]
    )

    # order_items
    op.alter_column(
        "order_items",
        "item_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "order_items",
        "qty",
        existing_type=sa.NUMERIC(precision=18, scale=6),
        type_=sa.Integer(),
        nullable=True,
    )
    op.alter_column(
        "order_items",
        "price",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=True,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "order_items",
        "discount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=True,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "order_items",
        "amount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        type_=sa.Numeric(precision=14, scale=2),
        nullable=True,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "order_items",
        "extras",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )

    # orders —— 先 drop 视图，再改列类型，最后重建视图
    op.execute("DROP VIEW IF EXISTS vw_routing_metrics_daily;")

    op.alter_column(
        "orders",
        "platform",
        existing_type=sa.VARCHAR(length=32),
        comment="平台标识（如 PDD / TAOBAO / JD）",
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "shop_id",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=64),
        comment="店铺 ID（字符串，与 stores.shop_id 对齐）",
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "ext_order_no",
        existing_type=sa.VARCHAR(length=128),
        comment="外部订单号 / 平台订单号",
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "status",
        existing_type=sa.TEXT(),
        type_=sa.String(length=32),
        nullable=True,
        comment="订单状态（CREATED / PAID / SHIPPED / CANCELED / RETURNED 等）",
        existing_server_default=sa.text("'CREATED'::text"),
    )
    op.alter_column(
        "orders",
        "buyer_name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=128),
        comment="买家姓名快照",
        existing_nullable=True,
    )
    op.alter_column(
        "orders",
        "buyer_phone",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=32),
        comment="买家电话快照",
        existing_nullable=True,
    )
    op.alter_column(
        "orders",
        "order_amount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        type_=sa.Numeric(precision=14, scale=2),
        nullable=True,
        comment="订单原始金额（含运费等，orders.order_amount）",
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "orders",
        "pay_amount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        type_=sa.Numeric(precision=14, scale=2),
        nullable=True,
        comment="订单实付金额（orders.pay_amount）",
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "orders",
        "trace_id",
        existing_type=sa.VARCHAR(length=64),
        comment="链路 trace_id，用于 TraceService 聚合",
        existing_nullable=True,
    )
    op.alter_column(
        "orders",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        comment="订单创建时间",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "orders",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="订单最近更新时间",
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )

    # 重建 vw_routing_metrics_daily 视图（来源：188b7099c71b）
    op.execute(
        """
        CREATE OR REPLACE VIEW vw_routing_metrics_daily AS
        SELECT
            date_trunc('day', o.created_at) AS day,
            o.platform,
            o.shop_id,
            COALESCE(s.route_mode, 'FALLBACK') AS route_mode,
            o.warehouse_id,
            COUNT(*) FILTER (WHERE o.warehouse_id IS NOT NULL) AS routed_orders,
            COUNT(*) FILTER (WHERE o.warehouse_id IS NULL)     AS failed_orders
        FROM orders o
        LEFT JOIN stores s
          ON s.platform = o.platform
         AND s.shop_id  = o.shop_id
        GROUP BY
            date_trunc('day', o.created_at),
            o.platform,
            o.shop_id,
            COALESCE(s.route_mode, 'FALLBACK'),
            o.warehouse_id;
        """
    )

    # purchase_order_lines / purchase_orders
    op.create_index(
        op.f("ix_purchase_order_lines_item_sku"),
        "purchase_order_lines",
        ["item_sku"],
        unique=False,
    )
    op.alter_column(
        "purchase_orders",
        "supplier_id",
        existing_type=sa.INTEGER(),
        comment="FK → suppliers.id，可为空",
        existing_nullable=True,
    )
    op.alter_column(
        "purchase_orders",
        "supplier_name",
        existing_type=sa.VARCHAR(length=255),
        comment="下单时的供应商名称快照，通常来自 suppliers.name",
        existing_nullable=True,
    )
    op.alter_column(
        "purchase_orders",
        "total_amount",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        comment="PO 汇总金额，由行表 line_amount 聚合",
        existing_nullable=True,
    )
    op.alter_column(
        "purchase_orders",
        "remark",
        existing_type=sa.VARCHAR(length=255),
        comment="采购单头部备注",
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_purchase_orders_warehouse_id"),
        "purchase_orders",
        ["warehouse_id"],
        unique=False,
    )

    # reservations
    op.alter_column(
        "reservations",
        "item_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "reservations",
        "qty",
        existing_type=sa.NUMERIC(precision=18, scale=6),
        type_=sa.Integer(),
        existing_nullable=True,
        existing_server_default=sa.text("0"),
    )

    # return_task_lines
    op.alter_column(
        "return_task_lines",
        "po_line_id",
        existing_type=sa.INTEGER(),
        comment="关联采购单行 purchase_order_lines.id，可为空",
        existing_nullable=True,
    )
    op.alter_column(
        "return_task_lines",
        "item_id",
        existing_type=sa.INTEGER(),
        comment="商品 ID",
        existing_nullable=False,
    )
    op.alter_column(
        "return_task_lines",
        "item_name",
        existing_type=sa.VARCHAR(length=255),
        comment="商品名称快照（可选）",
        existing_nullable=True,
    )
    op.alter_column(
        "return_task_lines",
        "batch_code",
        existing_type=sa.VARCHAR(length=64),
        comment="批次编码（可选，不强制）",
        existing_nullable=True,
    )
    op.alter_column(
        "return_task_lines",
        "expected_qty",
        existing_type=sa.INTEGER(),
        comment="计划退货数量（来自 PO 已收数量或人工录入）",
        existing_nullable=True,
    )
    op.alter_column(
        "return_task_lines",
        "picked_qty",
        existing_type=sa.INTEGER(),
        comment="已拣选/扫码准备退货的数量（可正可负）",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "return_task_lines",
        "committed_qty",
        existing_type=sa.INTEGER(),
        comment="最终出库数量（commit 时写入）",
        existing_nullable=True,
    )
    op.alter_column(
        "return_task_lines",
        "status",
        existing_type=sa.VARCHAR(length=32),
        comment="DRAFT / MATCHED / MISMATCH / COMMITTED",
        existing_nullable=False,
        existing_server_default=sa.text("'DRAFT'::character varying"),
    )
    op.alter_column(
        "return_task_lines",
        "remark",
        existing_type=sa.VARCHAR(length=255),
        comment="行备注",
        existing_nullable=True,
    )

    # return_tasks
    op.alter_column(
        "return_tasks",
        "po_id",
        existing_type=sa.INTEGER(),
        comment="关联采购单 purchase_orders.id，可为空",
        existing_nullable=True,
    )
    op.alter_column(
        "return_tasks",
        "supplier_id",
        existing_type=sa.INTEGER(),
        comment="供应商 ID（冗余自采购单）",
        existing_nullable=True,
    )
    op.alter_column(
        "return_tasks",
        "supplier_name",
        existing_type=sa.VARCHAR(length=255),
        comment="供应商名称快照（冗余自采购单）",
        existing_nullable=True,
    )
    op.alter_column(
        "return_tasks",
        "warehouse_id",
        existing_type=sa.INTEGER(),
        comment="退货仓库 ID",
        existing_nullable=False,
    )
    op.alter_column(
        "return_tasks",
        "status",
        existing_type=sa.VARCHAR(length=32),
        comment="DRAFT / COMMITTED / CANCELLED",
        existing_nullable=False,
        existing_server_default=sa.text("'DRAFT'::character varying"),
    )
    op.alter_column(
        "return_tasks",
        "remark",
        existing_type=sa.VARCHAR(length=255),
        comment="整单备注",
        existing_nullable=True,
    )

    # store_tokens / warehouses
    op.create_index(
        op.f("ix_store_tokens_platform"),
        "store_tokens",
        ["platform"],
        unique=False,
    )
    op.create_index(
        op.f("ix_store_tokens_store_id"),
        "store_tokens",
        ["store_id"],
        unique=False,
    )
    op.create_unique_constraint(None, "warehouses", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "warehouses", type_="unique")
    op.drop_index(op.f("ix_store_tokens_store_id"), table_name="store_tokens")
    op.drop_index(op.f("ix_store_tokens_platform"), table_name="store_tokens")
    op.alter_column(
        "return_tasks",
        "remark",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="整单备注",
        existing_nullable=True,
    )
    op.alter_column(
        "return_tasks",
        "status",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="DRAFT / COMMITTED / CANCELLED",
        existing_nullable=False,
        existing_server_default=sa.text("'DRAFT'::character varying"),
    )
    op.alter_column(
        "return_tasks",
        "warehouse_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="退货仓库 ID",
        existing_nullable=False,
    )
    op.alter_column(
        "return_tasks",
        "supplier_name",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="供应商名称快照（冗余自采购单）",
        existing_nullable=True,
    )
    op.alter_column(
        "return_tasks",
        "supplier_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="供应商 ID（冗余自采购单）",
        existing_nullable=True,
    )
    op.alter_column(
        "return_tasks",
        "po_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="关联采购单 purchase_orders.id，可为空",
        existing_nullable=True,
    )
    op.alter_column(
        "return_task_lines",
        "remark",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="行备注",
        existing_nullable=True,
    )
    op.alter_column(
        "return_task_lines",
        "status",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="DRAFT / MATCHED / MISMATCH / COMMITTED",
        existing_nullable=False,
        existing_server_default=sa.text("'DRAFT'::character varying"),
    )
    op.alter_column(
        "return_task_lines",
        "committed_qty",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="最终出库数量（commit 时写入）",
        existing_nullable=True,
    )
    op.alter_column(
        "return_task_lines",
        "picked_qty",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="已拣选/扫码准备退货的数量（可正可负）",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "return_task_lines",
        "expected_qty",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="计划退货数量（来自 PO 已收数量或人工录入）",
        existing_nullable=True,
    )
    op.alter_column(
        "return_task_lines",
        "batch_code",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="批次编码（可选，不强制）",
        existing_nullable=True,
    )
    op.alter_column(
        "return_task_lines",
        "item_name",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="商品名称快照（可选）",
        existing_nullable=True,
    )
    op.alter_column(
        "return_task_lines",
        "item_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="商品 ID",
        existing_nullable=False,
    )
    op.alter_column(
        "return_task_lines",
        "po_line_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="关联采购单行 purchase_order_lines.id，可为空",
        existing_nullable=True,
    )
    op.alter_column(
        "reservations",
        "qty",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=18, scale=6),
        existing_nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "reservations",
        "item_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_purchase_orders_warehouse_id"), table_name="purchase_orders"
    )
    op.alter_column(
        "purchase_orders",
        "remark",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="采购单头部备注",
        existing_nullable=True,
    )
    op.alter_column(
        "purchase_orders",
        "total_amount",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        comment=None,
        existing_comment="PO 汇总金额，由行表 line_amount 聚合",
        existing_nullable=True,
    )
    op.alter_column(
        "purchase_orders",
        "supplier_name",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="下单时的供应商名称快照，通常来自 suppliers.name",
        existing_nullable=True,
    )
    op.alter_column(
        "purchase_orders",
        "supplier_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="FK → suppliers.id，可为空",
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_purchase_order_lines_item_sku"),
        table_name="purchase_order_lines",
    )
    op.alter_column(
        "orders",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="订单最近更新时间",
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "orders",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="订单创建时间",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "orders",
        "trace_id",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="链路 trace_id，用于 TraceService 聚合",
        existing_nullable=True,
    )
    op.alter_column(
        "orders",
        "pay_amount",
        existing_type=sa.Numeric(precision=14, scale=2),
        type_=sa.NUMERIC(precision=12, scale=2),
        nullable=False,
        comment=None,
        existing_comment="订单实付金额（orders.pay_amount）",
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "orders",
        "order_amount",
        existing_type=sa.Numeric(precision=14, scale=2),
        type_=sa.NUMERIC(precision=12, scale=2),
        nullable=False,
        comment=None,
        existing_comment="订单原始金额（含运费等，orders.order_amount）",
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "orders",
        "buyer_phone",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="买家电话快照",
        existing_nullable=True,
    )
    op.alter_column(
        "orders",
        "buyer_name",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="买家姓名快照",
        existing_nullable=True,
    )
    op.alter_column(
        "orders",
        "status",
        existing_type=sa.String(length=32),
        type_=sa.TEXT(),
        nullable=False,
        comment=None,
        existing_comment="订单状态（CREATED / PAID / SHIPPED / CANCELED / RETURNED 等）",
        existing_server_default=sa.text("'CREATED'::text"),
    )
    op.alter_column(
        "orders",
        "ext_order_no",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="外部订单号 / 平台订单号",
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "shop_id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="店铺 ID（字符串，与 stores.shop_id 对齐）",
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "platform",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="平台标识（如 PDD / TAOBAO / JD）",
        existing_nullable=False,
    )
    op.alter_column(
        "order_items",
        "extras",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "order_items",
        "amount",
        existing_type=sa.Numeric(precision=14, scale=2),
        type_=sa.NUMERIC(precision=12, scale=2),
        nullable=False,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "order_items",
        "discount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=False,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "order_items",
        "price",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=False,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "order_items",
        "qty",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=18, scale=6),
        nullable=False,
    )
    op.alter_column(
        "order_items",
        "item_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "locations", type_="foreignkey")
    op.drop_index("ix_locations_wh", table_name="locations")
    op.drop_index("ix_locations_warehouse_id", table_name="locations")
    op.alter_column(
        "items",
        "weight_kg",
        existing_type=sa.NUMERIC(precision=10, scale=3),
        comment="单件净重（kg），用于运费预估（不含包材）",
        existing_comment="单件净重（kg），用于运费预估，不含包材",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_item_barcodes_item_id"), table_name="item_barcodes")
    op.drop_index("uq_item_barcodes_barcode", table_name="item_barcodes")
    op.alter_column(
        "item_barcodes",
        "kind",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="条码类型：EAN13 / UPC / INNER / CUSTOM ...",
        existing_nullable=False,
        existing_server_default=sa.text("'EAN13'::text"),
    )
    op.alter_column(
        "inventory_movements",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "inventory_movements",
        "movement_type",
        existing_type=sa.Enum(
            "RECEIPT", "SHIPMENT", "TRANSFER", "ADJUSTMENT", name="movementtype"
        ),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "inventory_movements",
        "item_sku",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_index("ix_event_store_topic", table_name="event_store")
    op.drop_index("ix_event_store_status", table_name="event_store")
    op.drop_index("ix_event_store_occurred", table_name="event_store")
    op.alter_column(
        "event_store",
        "trace_id",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "event_store",
        "status",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=32),
        nullable=True,
    )
    op.alter_column(
        "event_store",
        "headers",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "event_store",
        "payload",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "event_store",
        "key",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "event_store",
        "topic",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.drop_column("event_store", "last_error")
    op.drop_column("event_store", "attempts")
    op.alter_column(
        "event_error_log",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_constraint(None, "batches", type_="foreignkey")
    op.drop_constraint("uq_batches_item_wh_code", "batches", type_="unique")
    op.drop_index("ix_batches_item_wh_code", table_name="batches")
    op.alter_column(
        "batches",
        "supplier_lot",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
