"""items.id -> identity or fallback to nextval sequence (robust to existing seq)

Revision ID: 20251106_items_id_identity
Revises: 20251105_add_unique_on_stores_platform_name
Create Date: 2025-11-06 13:55:00+08
"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "20251106_items_id_identity"
down_revision = "20251105_add_unique_on_stores_platform_name"
branch_labels = None
depends_on = None


def upgrade():
    # 场景A：若不存在 items_id_seq，则使用「IDENTITY」创建并绑定
    # 场景B：若已存在 items_id_seq（可能来自旧脚本/测试），则不再强转 identity，
    #        直接将 items.id 默认值改为 nextval('items_id_seq') 并 OWNED BY items.id，
    #        再 setval 到 MAX(id)+1。两条路径都满足“自增默认值”的业务口径。

    op.execute("""
    DO $$
    DECLARE
      seq_exists boolean := EXISTS (
        SELECT 1
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'S'
          AND n.nspname = 'public'
          AND c.relname = 'items_id_seq'
      );
    BEGIN
      -- 统一移除旧的 identity/default（容错）
      BEGIN
        ALTER TABLE public.items ALTER COLUMN id DROP IDENTITY IF EXISTS;
      EXCEPTION WHEN undefined_column THEN
        RAISE EXCEPTION 'public.items.id not found';
      WHEN others THEN
        NULL;
      END;

      BEGIN
        ALTER TABLE public.items ALTER COLUMN id DROP DEFAULT;
      EXCEPTION WHEN others THEN
        NULL;
      END;

      IF NOT seq_exists THEN
        -- 场景A：没有同名序列，走 IDENTITY 路线
        ALTER TABLE public.items
          ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
          (SEQUENCE NAME public.items_id_seq);

        PERFORM setval(
          'public.items_id_seq',
          GREATEST(
            COALESCE((SELECT MAX(id) FROM public.items), 0) + 1,
            COALESCE((SELECT last_value FROM public.items_id_seq), 1)
          ),
          false
        );
        ALTER SEQUENCE public.items_id_seq OWNED BY public.items.id;

      ELSE
        -- 场景B：已有 public.items_id_seq，使用 nextval 作为默认值（不再创建 identity）
        ALTER SEQUENCE public.items_id_seq OWNED BY public.items.id;
        ALTER TABLE public.items
          ALTER COLUMN id SET DEFAULT nextval('public.items_id_seq'::regclass);

        PERFORM setval(
          'public.items_id_seq',
          GREATEST(
            COALESCE((SELECT MAX(id) FROM public.items), 0) + 1,
            COALESCE((SELECT last_value FROM public.items_id_seq), 1)
          ),
          false
        );
      END IF;
    END $$;
    """)


def downgrade():
    # 回滚：去掉 identity/默认值，并解除序列归属（不强删序列，避免影响历史）
    op.execute("""
    DO $$
    BEGIN
      BEGIN
        ALTER TABLE public.items ALTER COLUMN id DROP IDENTITY IF EXISTS;
      EXCEPTION WHEN others THEN
        NULL;
      END;

      BEGIN
        ALTER TABLE public.items ALTER COLUMN id DROP DEFAULT;
      EXCEPTION WHEN others THEN
        NULL;
      END;

      BEGIN
        ALTER SEQUENCE public.items_id_seq OWNED BY NONE;
      EXCEPTION WHEN undefined_table THEN
        NULL;
      WHEN others THEN
        NULL;
      END;
    END $$;
    """)
