"""finance shipping cost lines

Revision ID: 31c5a51a372d
Revises: 'ca210aca01b8'
Create Date: generated by script
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "31c5a51a372d"
down_revision: Union[str, Sequence[str], None] = 'ca210aca01b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TABLE_NAME = "finance_shipping_cost_lines"


def upgrade() -> None:
    op.create_table(
        TABLE_NAME,
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("shipping_record_id", sa.BigInteger(), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("shop_id", sa.String(length=64), nullable=False),
        sa.Column("shop_name", sa.String(length=256), nullable=True),
        sa.Column("order_ref", sa.String(length=128), nullable=False),
        sa.Column("package_no", sa.Integer(), nullable=False),
        sa.Column("tracking_no", sa.String(length=128), nullable=True),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_name", sa.String(length=100), nullable=False),
        sa.Column("shipping_provider_id", sa.Integer(), nullable=False),
        sa.Column("shipping_provider_code", sa.String(length=64), nullable=True),
        sa.Column("shipping_provider_name", sa.String(length=255), nullable=True),
        sa.Column("shipped_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("shipped_date", sa.Date(), nullable=False),
        sa.Column("dest_province", sa.String(length=64), nullable=True),
        sa.Column("dest_city", sa.String(length=64), nullable=True),
        sa.Column("gross_weight_kg", sa.Numeric(10, 3), nullable=True),
        sa.Column("cost_estimated", sa.Numeric(12, 2), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "calculated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint(
            "shipping_record_id",
            name="uq_finance_shipping_cost_lines_shipping_record_id",
        ),
    )

    op.create_index("ix_fsc_lines_platform_shop", TABLE_NAME, ["platform", "shop_id"])
    op.create_index("ix_fsc_lines_shop_id", TABLE_NAME, ["shop_id"])
    op.create_index("ix_fsc_lines_warehouse_id", TABLE_NAME, ["warehouse_id"])
    op.create_index("ix_fsc_lines_provider_id", TABLE_NAME, ["shipping_provider_id"])
    op.create_index("ix_fsc_lines_provider_code", TABLE_NAME, ["shipping_provider_code"])
    op.create_index("ix_fsc_lines_tracking_no", TABLE_NAME, ["tracking_no"])
    op.create_index("ix_fsc_lines_order_ref", TABLE_NAME, ["order_ref"])
    op.create_index("ix_fsc_lines_shipped_date", TABLE_NAME, ["shipped_date"])

    op.execute(
        """
        CREATE OR REPLACE FUNCTION finance_refresh_shipping_cost_line(p_shipping_record_id bigint)
        RETURNS void
        LANGUAGE plpgsql
        AS $$
        BEGIN
          INSERT INTO finance_shipping_cost_lines (
            shipping_record_id,
            platform,
            shop_id,
            shop_name,
            order_ref,
            package_no,
            tracking_no,
            warehouse_id,
            warehouse_name,
            shipping_provider_id,
            shipping_provider_code,
            shipping_provider_name,
            shipped_time,
            shipped_date,
            dest_province,
            dest_city,
            gross_weight_kg,
            cost_estimated,
            source_updated_at,
            calculated_at
          )
          SELECT
            sr.id AS shipping_record_id,
            sr.platform AS platform,
            sr.shop_id AS shop_id,
            s.name AS shop_name,
            sr.order_ref AS order_ref,
            sr.package_no AS package_no,
            sr.tracking_no AS tracking_no,
            sr.warehouse_id AS warehouse_id,
            COALESCE(w.name, '') AS warehouse_name,
            sr.shipping_provider_id AS shipping_provider_id,
            COALESCE(sp.shipping_provider_code, sr.shipping_provider_code) AS shipping_provider_code,
            COALESCE(sp.name, sr.shipping_provider_name) AS shipping_provider_name,
            sr.created_at AS shipped_time,
            DATE(sr.created_at) AS shipped_date,
            sr.dest_province AS dest_province,
            sr.dest_city AS dest_city,
            sr.gross_weight_kg AS gross_weight_kg,
            sr.cost_estimated AS cost_estimated,
            sr.created_at AS source_updated_at,
            now() AS calculated_at
          FROM shipping_records sr
          JOIN warehouses w
            ON w.id = sr.warehouse_id
          LEFT JOIN shipping_providers sp
            ON sp.id = sr.shipping_provider_id
          LEFT JOIN stores s
            ON upper(s.platform) = upper(sr.platform)
           AND btrim(CAST(s.shop_id AS text)) = btrim(CAST(sr.shop_id AS text))
          WHERE sr.id = p_shipping_record_id
          ON CONFLICT (shipping_record_id) DO UPDATE SET
            platform = EXCLUDED.platform,
            shop_id = EXCLUDED.shop_id,
            shop_name = EXCLUDED.shop_name,
            order_ref = EXCLUDED.order_ref,
            package_no = EXCLUDED.package_no,
            tracking_no = EXCLUDED.tracking_no,
            warehouse_id = EXCLUDED.warehouse_id,
            warehouse_name = EXCLUDED.warehouse_name,
            shipping_provider_id = EXCLUDED.shipping_provider_id,
            shipping_provider_code = EXCLUDED.shipping_provider_code,
            shipping_provider_name = EXCLUDED.shipping_provider_name,
            shipped_time = EXCLUDED.shipped_time,
            shipped_date = EXCLUDED.shipped_date,
            dest_province = EXCLUDED.dest_province,
            dest_city = EXCLUDED.dest_city,
            gross_weight_kg = EXCLUDED.gross_weight_kg,
            cost_estimated = EXCLUDED.cost_estimated,
            source_updated_at = EXCLUDED.source_updated_at,
            calculated_at = now();
        END;
        $$;
        """
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION finance_trg_shipping_cost_line_upsert()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
          PERFORM finance_refresh_shipping_cost_line(NEW.id);
          RETURN NEW;
        END;
        $$;
        """
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION finance_trg_shipping_cost_line_delete()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
          DELETE FROM finance_shipping_cost_lines
          WHERE shipping_record_id = OLD.id;
          RETURN OLD;
        END;
        $$;
        """
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION finance_trg_shipping_cost_warehouse_refresh()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
          v_record_id bigint;
        BEGIN
          FOR v_record_id IN
            SELECT id FROM shipping_records WHERE warehouse_id = NEW.id
          LOOP
            PERFORM finance_refresh_shipping_cost_line(v_record_id);
          END LOOP;
          RETURN NEW;
        END;
        $$;
        """
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION finance_trg_shipping_cost_provider_refresh()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
          v_record_id bigint;
        BEGIN
          FOR v_record_id IN
            SELECT id FROM shipping_records WHERE shipping_provider_id = NEW.id
          LOOP
            PERFORM finance_refresh_shipping_cost_line(v_record_id);
          END LOOP;
          RETURN NEW;
        END;
        $$;
        """
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION finance_trg_shipping_cost_store_refresh()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
          v_record_id bigint;
        BEGIN
          IF TG_OP IN ('INSERT', 'UPDATE') THEN
            FOR v_record_id IN
              SELECT id
              FROM shipping_records
              WHERE upper(platform) = upper(NEW.platform)
                AND btrim(CAST(shop_id AS text)) = btrim(CAST(NEW.shop_id AS text))
            LOOP
              PERFORM finance_refresh_shipping_cost_line(v_record_id);
            END LOOP;
          END IF;

          IF TG_OP IN ('UPDATE', 'DELETE') THEN
            FOR v_record_id IN
              SELECT id
              FROM shipping_records
              WHERE upper(platform) = upper(OLD.platform)
                AND btrim(CAST(shop_id AS text)) = btrim(CAST(OLD.shop_id AS text))
            LOOP
              PERFORM finance_refresh_shipping_cost_line(v_record_id);
            END LOOP;
          END IF;

          IF TG_OP = 'DELETE' THEN
            RETURN OLD;
          END IF;
          RETURN NEW;
        END;
        $$;
        """
    )

    op.execute(
        """
        CREATE TRIGGER trg_fsc_lines_shipping_records_upsert
        AFTER INSERT OR UPDATE ON shipping_records
        FOR EACH ROW
        EXECUTE FUNCTION finance_trg_shipping_cost_line_upsert()
        """
    )

    op.execute(
        """
        CREATE TRIGGER trg_fsc_lines_shipping_records_delete
        AFTER DELETE ON shipping_records
        FOR EACH ROW
        EXECUTE FUNCTION finance_trg_shipping_cost_line_delete()
        """
    )

    op.execute(
        """
        CREATE TRIGGER trg_fsc_lines_warehouse_refresh
        AFTER UPDATE OF name
        ON warehouses
        FOR EACH ROW
        EXECUTE FUNCTION finance_trg_shipping_cost_warehouse_refresh()
        """
    )

    op.execute(
        """
        CREATE TRIGGER trg_fsc_lines_provider_refresh
        AFTER UPDATE OF name, shipping_provider_code
        ON shipping_providers
        FOR EACH ROW
        EXECUTE FUNCTION finance_trg_shipping_cost_provider_refresh()
        """
    )

    op.execute(
        """
        CREATE TRIGGER trg_fsc_lines_store_refresh
        AFTER INSERT OR UPDATE OF name, platform, shop_id OR DELETE
        ON stores
        FOR EACH ROW
        EXECUTE FUNCTION finance_trg_shipping_cost_store_refresh()
        """
    )

    op.execute(
        """
        SELECT finance_refresh_shipping_cost_line(sr.id)
        FROM shipping_records sr
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_fsc_lines_store_refresh ON stores")
    op.execute("DROP TRIGGER IF EXISTS trg_fsc_lines_provider_refresh ON shipping_providers")
    op.execute("DROP TRIGGER IF EXISTS trg_fsc_lines_warehouse_refresh ON warehouses")
    op.execute("DROP TRIGGER IF EXISTS trg_fsc_lines_shipping_records_delete ON shipping_records")
    op.execute("DROP TRIGGER IF EXISTS trg_fsc_lines_shipping_records_upsert ON shipping_records")

    op.execute("DROP FUNCTION IF EXISTS finance_trg_shipping_cost_store_refresh()")
    op.execute("DROP FUNCTION IF EXISTS finance_trg_shipping_cost_provider_refresh()")
    op.execute("DROP FUNCTION IF EXISTS finance_trg_shipping_cost_warehouse_refresh()")
    op.execute("DROP FUNCTION IF EXISTS finance_trg_shipping_cost_line_delete()")
    op.execute("DROP FUNCTION IF EXISTS finance_trg_shipping_cost_line_upsert()")
    op.execute("DROP FUNCTION IF EXISTS finance_refresh_shipping_cost_line(bigint)")

    op.drop_index("ix_fsc_lines_shipped_date", table_name=TABLE_NAME)
    op.drop_index("ix_fsc_lines_order_ref", table_name=TABLE_NAME)
    op.drop_index("ix_fsc_lines_tracking_no", table_name=TABLE_NAME)
    op.drop_index("ix_fsc_lines_provider_code", table_name=TABLE_NAME)
    op.drop_index("ix_fsc_lines_provider_id", table_name=TABLE_NAME)
    op.drop_index("ix_fsc_lines_warehouse_id", table_name=TABLE_NAME)
    op.drop_index("ix_fsc_lines_shop_id", table_name=TABLE_NAME)
    op.drop_index("ix_fsc_lines_platform_shop", table_name=TABLE_NAME)

    op.drop_table(TABLE_NAME)
