"""add_internal_outbound_foreign_keys

Revision ID: 4cbadbf3083e
Revises: 66a46d33178e
Create Date: 2025-12-09 22:28:41.820673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbadbf3083e'
down_revision: Union[str, Sequence[str], None] = '66a46d33178e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'internal_outbound_docs', 'users', ['canceled_by'], ['id'])
    op.create_foreign_key(None, 'internal_outbound_docs', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'internal_outbound_docs', 'users', ['confirmed_by'], ['id'])
    op.create_foreign_key(None, 'internal_outbound_docs', 'users', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'internal_outbound_lines', 'items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'internal_outbound_lines', 'internal_outbound_docs', ['doc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'internal_outbound_lines', type_='foreignkey')
    op.drop_constraint(None, 'internal_outbound_lines', type_='foreignkey')
    op.drop_constraint(None, 'internal_outbound_docs', type_='foreignkey')
    op.drop_constraint(None, 'internal_outbound_docs', type_='foreignkey')
    op.drop_constraint(None, 'internal_outbound_docs', type_='foreignkey')
    op.drop_constraint(None, 'internal_outbound_docs', type_='foreignkey')
    # ### end Alembic commands ###
