"""phase3_9_drift_cleanup

Revision ID: 59ba81265708
Revises: e0c9c01ced40
Create Date: 2025-11-16 15:44:32.798557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "59ba81265708"
down_revision: Union[str, Sequence[str], None] = "e0c9c01ced40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted ###

    # channel_inventory indexes
    op.create_index(
        op.f("ix_channel_inventory_item_id"),
        "channel_inventory",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_channel_inventory_store_id"),
        "channel_inventory",
        ["store_id"],
        unique=False,
    )
    op.create_index(
        "ix_channel_inventory_store_item",
        "channel_inventory",
        ["store_id", "item_id"],
        unique=False,
    )

    # event_log
    op.alter_column(
        "event_log",
        "source",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "event_log",
        "message",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.create_index("ix_event_log_level", "event_log", ["level"], unique=False)
    op.create_index("ix_event_log_source", "event_log", ["source"], unique=False)
    op.create_index("ix_event_log_time", "event_log", ["occurred_at"], unique=False)

    # event_store
    op.alter_column(
        "event_store",
        "topic",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "event_store",
        "key",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "event_store",
        "status",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.Text(),
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING'::character varying"),
    )
    op.alter_column(
        "event_store",
        "trace_id",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.create_index(
        "ix_event_store_occurred",
        "event_store",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_event_store_status",
        "event_store",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_event_store_topic",
        "event_store",
        ["topic"],
        unique=False,
    )

    # item_barcodes
    op.alter_column(
        "item_barcodes",
        "kind",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="EAN13 / UPC / INNER / CUSTOM ...",
        existing_nullable=False,
        existing_server_default=sa.text("'EAN13'::text"),
    )
    op.create_index(
        "item_barcodes_barcode_key",
        "item_barcodes",
        ["barcode"],
        unique=True,
    )
    op.create_foreign_key(
        None,
        "item_barcodes",
        "items",
        ["item_id"],
        ["id"],
    )

    # locations
    op.create_index(
        "ix_locations_warehouse_id",
        "locations",
        ["warehouse_id"],
        unique=False,
    )
    op.create_index(
        "ix_locations_wh",
        "locations",
        ["warehouse_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "locations",
        "warehouses",
        ["warehouse_id"],
        ["id"],
    )

    # order_lines & order_state_snapshot
    op.create_index("ix_order_lines_item", "order_lines", ["item_id"], unique=False)
    op.create_foreign_key(
        None,
        "order_lines",
        "orders",
        ["order_id"],
        ["id"],
    )
    op.create_index(
        "ix_order_state_snapshot_no",
        "order_state_snapshot",
        ["order_no"],
        unique=False,
    )
    op.create_index(
        "ix_order_state_snapshot_state",
        "order_state_snapshot",
        ["state"],
        unique=False,
    )

    # outbound_commits
    op.alter_column(
        "outbound_commits",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "outbound_commits",
        "state",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "outbound_commits",
        "ref",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.Text(),
        nullable=True,
    )
    op.create_index(
        "ix_outbound_commits_item",
        "outbound_commits",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        "ix_outbound_commits_loc",
        "outbound_commits",
        ["location_id"],
        unique=False,
    )
    op.create_index(
        "ix_outbound_commits_state",
        "outbound_commits",
        ["state"],
        unique=False,
    )

    # outbound_ship_ops
    op.alter_column(
        "outbound_ship_ops",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "outbound_ship_ops",
        "store_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "outbound_ship_ops",
        "ref",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.Text(),
        nullable=True,
    )
    op.create_index(
        "ix_outbound_ship_ops_item",
        "outbound_ship_ops",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        "ix_outbound_ship_ops_ref",
        "outbound_ship_ops",
        ["ref"],
        unique=False,
    )
    op.create_index(
        "ix_outbound_ship_ops_store",
        "outbound_ship_ops",
        ["store_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "outbound_ship_ops",
        "stores",
        ["store_id"],
        ["id"],
    )

    # pick_tasks + pick_task_lines
    op.create_index(
        "ix_pick_task_lines_item",
        "pick_task_lines",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        "ix_pick_task_lines_status",
        "pick_task_lines",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_pick_task_lines_task",
        "pick_task_lines",
        ["task_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "pick_task_lines",
        "pick_tasks",
        ["task_id"],
        ["id"],
    )
    op.alter_column(
        "pick_tasks",
        "source",
        existing_type=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("'SYSTEM'::text"),
    )
    op.create_index(
        "ix_pick_tasks_assigned",
        "pick_tasks",
        ["assigned_to"],
        unique=False,
    )
    op.create_index(
        "ix_pick_tasks_status",
        "pick_tasks",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_pick_tasks_wh_prio",
        "pick_tasks",
        ["warehouse_id", "priority"],
        unique=False,
    )

    # platform_shops
    op.alter_column(
        "platform_shops",
        "platform",
        existing_type=sa.VARCHAR(length=32),
        comment="平台类型（PDD/TAOBAO/JD 等）",
        existing_nullable=False,
    )
    op.alter_column(
        "platform_shops",
        "shop_id",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=128),
        comment="平台店铺唯一 ID",
        existing_nullable=False,
    )
    op.alter_column(
        "platform_shops",
        "rate_limit_qps",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("5"),
    )
    op.create_index(
        "ix_platform_shops_shop_id",
        "platform_shops",
        ["shop_id"],
        unique=False,
    )

    # store_items
    op.create_index(
        op.f("ix_store_items_item_id"),
        "store_items",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_store_items_store_id"),
        "store_items",
        ["store_id"],
        unique=False,
    )
    op.create_index(
        "ix_store_items_store_item",
        "store_items",
        ["store_id", "item_id"],
        unique=False,
    )

    # store_warehouse
    op.add_column(
        "store_warehouse",
        sa.Column("is_top", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.alter_column(
        "store_warehouse",
        "store_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "store_warehouse",
        "warehouse_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )

    # stores.shop_id：先填补 NULL，再加 NOT NULL 约束
    op.execute(
        "UPDATE stores SET shop_id = 'LOCAL-' || id::text WHERE shop_id IS NULL"
    )
    op.alter_column(
        "stores",
        "shop_id",
        existing_type=sa.VARCHAR(length=128),
        nullable=False,
    )
    op.alter_column(
        "stores",
        "name",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=256),
        existing_nullable=False,
    )
    op.create_index("ix_stores_shop", "stores", ["shop_id"], unique=False)

    # reservation_lines：统一的唯一约束 (reservation_id, ref_line)
    # 为防止已有同名索引，先删 index，再建 unique constraint
    op.execute("DROP INDEX IF EXISTS ix_reservation_lines_res_refline")
    op.create_unique_constraint(
        "ix_reservation_lines_res_refline",
        "reservation_lines",
        ["reservation_id", "ref_line"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted ###

    # reservation_lines rollback：删 unique，重建普通索引
    op.drop_constraint(
        "ix_reservation_lines_res_refline",
        "reservation_lines",
        type_="unique",
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_reservation_lines_res_refline "
        "ON reservation_lines (reservation_id, ref_line)"
    )

    op.drop_index("ix_stores_shop", table_name="stores")
    op.alter_column(
        "stores",
        "name",
        existing_type=sa.String(length=256),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    op.alter_column(
        "stores",
        "shop_id",
        existing_type=sa.VARCHAR(length=128),
        nullable=True,
    )

    op.alter_column(
        "store_warehouse",
        "warehouse_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.alter_column(
        "store_warehouse",
        "store_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.drop_column("store_warehouse", "is_top")

    op.drop_index("ix_store_items_store_item", table_name="store_items")
    op.drop_index(op.f("ix_store_items_store_id"), table_name="store_items")
    op.drop_index(op.f("ix_store_items_item_id"), table_name="store_items")

    op.drop_index("ix_platform_shops_shop_id", table_name="platform_shops")
    op.alter_column(
        "platform_shops",
        "rate_limit_qps",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("5"),
    )
    op.alter_column(
        "platform_shops",
        "shop_id",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="平台店铺唯一 ID",
        existing_nullable=False,
    )
    op.alter_column(
        "platform_shops",
        "platform",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="平台类型（PDD/TAOBAO/JD 等）",
        existing_nullable=False,
    )

    op.drop_index("ix_pick_tasks_wh_prio", table_name="pick_tasks")
    op.drop_index("ix_pick_tasks_status", table_name="pick_tasks")
    op.drop_index("ix_pick_tasks_assigned", table_name="pick_tasks")
    op.alter_column(
        "pick_tasks",
        "source",
        existing_type=sa.TEXT(),
        nullable=False,
        existing_server_default=sa.text("'SYSTEM'::text"),
    )
    op.drop_constraint(None, "pick_task_lines", type_="foreignkey")
    op.drop_index("ix_pick_task_lines_task", table_name="pick_task_lines")
    op.drop_index("ix_pick_task_lines_status", table_name="pick_task_lines")
    op.drop_index("ix_pick_task_lines_item", table_name="pick_task_lines")

    op.drop_constraint(None, "outbound_ship_ops", type_="foreignkey")
    op.drop_index("ix_outbound_ship_ops_store", table_name="outbound_ship_ops")
    op.drop_index("ix_outbound_ship_ops_ref", table_name="outbound_ship_ops")
    op.drop_index("ix_outbound_ship_ops_item", table_name="outbound_ship_ops")
    op.alter_column(
        "outbound_ship_ops",
        "ref",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=128),
        nullable=False,
    )
    op.alter_column(
        "outbound_ship_ops",
        "store_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "outbound_ship_ops",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )

    op.drop_index("ix_outbound_commits_state", table_name="outbound_commits")
    op.drop_index("ix_outbound_commits_loc", table_name="outbound_commits")
    op.drop_index("ix_outbound_commits_item", table_name="outbound_commits")
    op.alter_column(
        "outbound_commits",
        "ref",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.alter_column(
        "outbound_commits",
        "state",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=32),
        existing_nullable=True,
    )
    op.alter_column(
        "outbound_commits",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )

    op.drop_index("ix_order_state_snapshot_state", table_name="order_state_snapshot")
    op.drop_index("ix_order_state_snapshot_no", table_name="order_state_snapshot")
    op.drop_constraint(None, "order_lines", type_="foreignkey")
    op.drop_index("ix_order_lines_item", table_name="order_lines")
    op.drop_constraint(None, "locations", type_="foreignkey")
    op.drop_index("ix_locations_wh", table_name="locations")
    op.drop_index("ix_locations_warehouse_id", table_name="locations")
    op.drop_constraint(None, "item_barcodes", type_="foreignkey")
    op.drop_index("item_barcodes_barcode_key", table_name="item_barcodes")
    op.alter_column(
        "item_barcodes",
        "kind",
        existing_type=sa.TEXT(),
        comment="EAN13 / UPC / INNER / CUSTOM ...",
        existing_nullable=False,
        existing_server_default=sa.text("'EAN13'::text"),
    )

    op.drop_index("ix_event_store_topic", table_name="event_store")
    op.drop_index("ix_event_store_status", table_name="event_store")
    op.drop_index("ix_event_store_occurred", table_name="event_store")
    op.alter_column(
        "event_store",
        "trace_id",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=64),
        existing_nullable=True,
    )
    op.alter_column(
        "event_store",
        "status",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING'::character varying"),
    )
    op.alter_column(
        "event_store",
        "key",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "event_store",
        "topic",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )

    op.drop_index("ix_event_log_time", table_name="event_log")
    op.drop_index("ix_event_log_source", table_name="event_log")
    op.drop_index("ix_event_log_level", table_name="event_log")
    op.alter_column(
        "event_log",
        "message",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "event_log",
        "source",
        existing_type=sa.TEXT(),
        nullable=False,
    )

    op.drop_index("ix_channel_inventory_store_item", table_name="channel_inventory")
    op.drop_index(
        op.f("ix_channel_inventory_store_id"),
        table_name="channel_inventory",
    )
    op.drop_index(
        op.f("ix_channel_inventory_item_id"),
        table_name="channel_inventory",
    )
    # ### end Alembic commands ###
