"""rename shipping provider code contract

Revision ID: ca210aca01b8
Revises: '3f940aff7149'
Create Date: generated by script
"""

from typing import Sequence, Union

from alembic import op


revision: str = "ca210aca01b8"
down_revision: Union[str, Sequence[str], None] = '3f940aff7149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _rename_column_if_exists(table_name: str, old_name: str, new_name: str) -> None:
    op.execute(
        f"""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = '{table_name}'
                  AND column_name = '{old_name}'
            )
            AND NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = '{table_name}'
                  AND column_name = '{new_name}'
            )
            THEN
                EXECUTE 'ALTER TABLE public.' || quote_ident('{table_name}')
                    || ' RENAME COLUMN ' || quote_ident('{old_name}')
                    || ' TO ' || quote_ident('{new_name}');
            END IF;
        END
        $$;
        """
    )


def _rename_constraint_if_exists(table_name: str, old_name: str, new_name: str) -> None:
    op.execute(
        f"""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint c
                JOIN pg_class t ON t.oid = c.conrelid
                JOIN pg_namespace n ON n.oid = t.relnamespace
                WHERE n.nspname = 'public'
                  AND t.relname = '{table_name}'
                  AND c.conname = '{old_name}'
            )
            AND NOT EXISTS (
                SELECT 1
                FROM pg_constraint c
                JOIN pg_class t ON t.oid = c.conrelid
                JOIN pg_namespace n ON n.oid = t.relnamespace
                WHERE n.nspname = 'public'
                  AND t.relname = '{table_name}'
                  AND c.conname = '{new_name}'
            )
            THEN
                EXECUTE 'ALTER TABLE public.' || quote_ident('{table_name}')
                    || ' RENAME CONSTRAINT ' || quote_ident('{old_name}')
                    || ' TO ' || quote_ident('{new_name}');
            END IF;
        END
        $$;
        """
    )


def _rename_index_if_exists(old_name: str, new_name: str) -> None:
    op.execute(
        f"""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_class i
                JOIN pg_namespace n ON n.oid = i.relnamespace
                WHERE n.nspname = 'public'
                  AND i.relkind = 'i'
                  AND i.relname = '{old_name}'
            )
            AND NOT EXISTS (
                SELECT 1
                FROM pg_class i
                JOIN pg_namespace n ON n.oid = i.relnamespace
                WHERE n.nspname = 'public'
                  AND i.relkind = 'i'
                  AND i.relname = '{new_name}'
            )
            THEN
                EXECUTE 'ALTER INDEX public.' || quote_ident('{old_name}')
                    || ' RENAME TO ' || quote_ident('{new_name}');
            END IF;
        END
        $$;
        """
    )


def upgrade() -> None:
    _rename_column_if_exists("shipping_providers", "code", "shipping_provider_code")
    _rename_constraint_if_exists("shipping_providers", "uq_shipping_providers_code", "uq_shipping_providers_shipping_provider_code")
    _rename_constraint_if_exists("shipping_providers", "ck_shipping_providers_code_trimmed", "ck_shipping_providers_shipping_provider_code_trimmed")
    _rename_constraint_if_exists("shipping_providers", "ck_shipping_providers_code_upper", "ck_shipping_providers_shipping_provider_code_upper")
    _rename_index_if_exists("uq_shipping_providers_code", "uq_shipping_providers_shipping_provider_code")

    _rename_column_if_exists("shipping_records", "carrier_code", "shipping_provider_code")
    _rename_column_if_exists("shipping_records", "carrier_name", "shipping_provider_name")

    _rename_column_if_exists("carrier_bill_items", "carrier_code", "shipping_provider_code")
    _rename_column_if_exists("shipping_record_reconciliations", "carrier_code", "shipping_provider_code")
    _rename_column_if_exists("shipping_bill_reconciliation_histories", "carrier_code", "shipping_provider_code")

    _rename_column_if_exists("transport_shipments", "carrier_code", "shipping_provider_code")
    _rename_column_if_exists("transport_shipments", "carrier_name", "shipping_provider_name")

    _rename_column_if_exists("order_logistics", "carrier_code", "shipping_provider_code")
    _rename_column_if_exists("order_logistics", "carrier_name", "shipping_provider_name")

    _rename_constraint_if_exists("carrier_bill_items", "uq_carrier_bill_items_carrier_tracking", "uq_carrier_bill_items_shipping_provider_tracking")
    _rename_index_if_exists("uq_carrier_bill_items_carrier_tracking", "uq_carrier_bill_items_shipping_provider_tracking")
    _rename_index_if_exists("ix_carrier_bill_items_carrier_tracking", "ix_carrier_bill_items_shipping_provider_tracking")
    _rename_index_if_exists("ix_shipping_record_reconciliations_carrier_status", "ix_shipping_record_reconciliations_provider_status")
    _rename_index_if_exists("ix_shipping_bill_reconciliation_histories_carrier_tracking", "ix_shipping_bill_reconciliation_histories_provider_tracking")


def downgrade() -> None:
    _rename_index_if_exists("ix_shipping_bill_reconciliation_histories_provider_tracking", "ix_shipping_bill_reconciliation_histories_carrier_tracking")
    _rename_index_if_exists("ix_shipping_record_reconciliations_provider_status", "ix_shipping_record_reconciliations_carrier_status")
    _rename_index_if_exists("ix_carrier_bill_items_shipping_provider_tracking", "ix_carrier_bill_items_carrier_tracking")
    _rename_index_if_exists("uq_carrier_bill_items_shipping_provider_tracking", "uq_carrier_bill_items_carrier_tracking")
    _rename_constraint_if_exists("carrier_bill_items", "uq_carrier_bill_items_shipping_provider_tracking", "uq_carrier_bill_items_carrier_tracking")

    _rename_column_if_exists("order_logistics", "shipping_provider_name", "carrier_name")
    _rename_column_if_exists("order_logistics", "shipping_provider_code", "carrier_code")

    _rename_column_if_exists("transport_shipments", "shipping_provider_name", "carrier_name")
    _rename_column_if_exists("transport_shipments", "shipping_provider_code", "carrier_code")

    _rename_column_if_exists("shipping_bill_reconciliation_histories", "shipping_provider_code", "carrier_code")
    _rename_column_if_exists("shipping_record_reconciliations", "shipping_provider_code", "carrier_code")
    _rename_column_if_exists("carrier_bill_items", "shipping_provider_code", "carrier_code")

    _rename_column_if_exists("shipping_records", "shipping_provider_name", "carrier_name")
    _rename_column_if_exists("shipping_records", "shipping_provider_code", "carrier_code")

    _rename_index_if_exists("uq_shipping_providers_shipping_provider_code", "uq_shipping_providers_code")
    _rename_constraint_if_exists("shipping_providers", "ck_shipping_providers_shipping_provider_code_upper", "ck_shipping_providers_code_upper")
    _rename_constraint_if_exists("shipping_providers", "ck_shipping_providers_shipping_provider_code_trimmed", "ck_shipping_providers_code_trimmed")
    _rename_constraint_if_exists("shipping_providers", "uq_shipping_providers_shipping_provider_code", "uq_shipping_providers_code")
    _rename_column_if_exists("shipping_providers", "shipping_provider_code", "code")
