"""sync item model schema

Revision ID: eab26128e392
Revises: 3cc7bae645cc
Create Date: 2025-11-24 20:05:08.135499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab26128e392'
down_revision: Union[str, Sequence[str], None] = '3cc7bae645cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation_allocations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('reservation_allocations', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('reservation_allocations', 'warehouse_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('reservation_allocations', 'location_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('reservation_allocations', 'qty',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation_allocations', 'qty',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('reservation_allocations', 'location_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('reservation_allocations', 'warehouse_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('reservation_allocations', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('reservation_allocations', 'updated_at')
    # ### end Alembic commands ###
