"""finance shipping cost line breakdown

Revision ID: ecd37dd41170
Revises: '31c5a51a372d'
Create Date: generated by script
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "ecd37dd41170"
down_revision: Union[str, Sequence[str], None] = '31c5a51a372d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TABLE_NAME = "finance_shipping_cost_lines"


def upgrade() -> None:
    op.add_column(
        TABLE_NAME,
        sa.Column("freight_estimated", sa.Numeric(12, 2), nullable=True),
    )
    op.add_column(
        TABLE_NAME,
        sa.Column("surcharge_estimated", sa.Numeric(12, 2), nullable=True),
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION finance_refresh_shipping_cost_line(p_shipping_record_id bigint)
        RETURNS void
        LANGUAGE plpgsql
        AS $$
        BEGIN
          INSERT INTO finance_shipping_cost_lines (
            shipping_record_id,
            platform,
            shop_id,
            shop_name,
            order_ref,
            package_no,
            tracking_no,
            warehouse_id,
            warehouse_name,
            shipping_provider_id,
            shipping_provider_code,
            shipping_provider_name,
            shipped_time,
            shipped_date,
            dest_province,
            dest_city,
            gross_weight_kg,
            freight_estimated,
            surcharge_estimated,
            cost_estimated,
            source_updated_at,
            calculated_at
          )
          SELECT
            sr.id AS shipping_record_id,
            sr.platform AS platform,
            sr.shop_id AS shop_id,
            s.name AS shop_name,
            sr.order_ref AS order_ref,
            sr.package_no AS package_no,
            sr.tracking_no AS tracking_no,
            sr.warehouse_id AS warehouse_id,
            COALESCE(w.name, '') AS warehouse_name,
            sr.shipping_provider_id AS shipping_provider_id,
            COALESCE(sp.shipping_provider_code, sr.shipping_provider_code) AS shipping_provider_code,
            COALESCE(sp.name, sr.shipping_provider_name) AS shipping_provider_name,
            sr.created_at AS shipped_time,
            DATE(sr.created_at) AS shipped_date,
            sr.dest_province AS dest_province,
            sr.dest_city AS dest_city,
            sr.gross_weight_kg AS gross_weight_kg,
            sr.freight_estimated AS freight_estimated,
            sr.surcharge_estimated AS surcharge_estimated,
            sr.cost_estimated AS cost_estimated,
            sr.created_at AS source_updated_at,
            now() AS calculated_at
          FROM shipping_records sr
          JOIN warehouses w
            ON w.id = sr.warehouse_id
          LEFT JOIN shipping_providers sp
            ON sp.id = sr.shipping_provider_id
          LEFT JOIN stores s
            ON upper(s.platform) = upper(sr.platform)
           AND btrim(CAST(s.shop_id AS text)) = btrim(CAST(sr.shop_id AS text))
          WHERE sr.id = p_shipping_record_id
          ON CONFLICT (shipping_record_id) DO UPDATE SET
            platform = EXCLUDED.platform,
            shop_id = EXCLUDED.shop_id,
            shop_name = EXCLUDED.shop_name,
            order_ref = EXCLUDED.order_ref,
            package_no = EXCLUDED.package_no,
            tracking_no = EXCLUDED.tracking_no,
            warehouse_id = EXCLUDED.warehouse_id,
            warehouse_name = EXCLUDED.warehouse_name,
            shipping_provider_id = EXCLUDED.shipping_provider_id,
            shipping_provider_code = EXCLUDED.shipping_provider_code,
            shipping_provider_name = EXCLUDED.shipping_provider_name,
            shipped_time = EXCLUDED.shipped_time,
            shipped_date = EXCLUDED.shipped_date,
            dest_province = EXCLUDED.dest_province,
            dest_city = EXCLUDED.dest_city,
            gross_weight_kg = EXCLUDED.gross_weight_kg,
            freight_estimated = EXCLUDED.freight_estimated,
            surcharge_estimated = EXCLUDED.surcharge_estimated,
            cost_estimated = EXCLUDED.cost_estimated,
            source_updated_at = EXCLUDED.source_updated_at,
            calculated_at = now();
        END;
        $$;
        """
    )

    op.execute(
        """
        SELECT finance_refresh_shipping_cost_line(sr.id)
        FROM shipping_records sr
        """
    )


def downgrade() -> None:
    op.execute(
        """
        CREATE OR REPLACE FUNCTION finance_refresh_shipping_cost_line(p_shipping_record_id bigint)
        RETURNS void
        LANGUAGE plpgsql
        AS $$
        BEGIN
          INSERT INTO finance_shipping_cost_lines (
            shipping_record_id,
            platform,
            shop_id,
            shop_name,
            order_ref,
            package_no,
            tracking_no,
            warehouse_id,
            warehouse_name,
            shipping_provider_id,
            shipping_provider_code,
            shipping_provider_name,
            shipped_time,
            shipped_date,
            dest_province,
            dest_city,
            gross_weight_kg,
            cost_estimated,
            source_updated_at,
            calculated_at
          )
          SELECT
            sr.id AS shipping_record_id,
            sr.platform AS platform,
            sr.shop_id AS shop_id,
            s.name AS shop_name,
            sr.order_ref AS order_ref,
            sr.package_no AS package_no,
            sr.tracking_no AS tracking_no,
            sr.warehouse_id AS warehouse_id,
            COALESCE(w.name, '') AS warehouse_name,
            sr.shipping_provider_id AS shipping_provider_id,
            COALESCE(sp.shipping_provider_code, sr.shipping_provider_code) AS shipping_provider_code,
            COALESCE(sp.name, sr.shipping_provider_name) AS shipping_provider_name,
            sr.created_at AS shipped_time,
            DATE(sr.created_at) AS shipped_date,
            sr.dest_province AS dest_province,
            sr.dest_city AS dest_city,
            sr.gross_weight_kg AS gross_weight_kg,
            sr.cost_estimated AS cost_estimated,
            sr.created_at AS source_updated_at,
            now() AS calculated_at
          FROM shipping_records sr
          JOIN warehouses w
            ON w.id = sr.warehouse_id
          LEFT JOIN shipping_providers sp
            ON sp.id = sr.shipping_provider_id
          LEFT JOIN stores s
            ON upper(s.platform) = upper(sr.platform)
           AND btrim(CAST(s.shop_id AS text)) = btrim(CAST(sr.shop_id AS text))
          WHERE sr.id = p_shipping_record_id
          ON CONFLICT (shipping_record_id) DO UPDATE SET
            platform = EXCLUDED.platform,
            shop_id = EXCLUDED.shop_id,
            shop_name = EXCLUDED.shop_name,
            order_ref = EXCLUDED.order_ref,
            package_no = EXCLUDED.package_no,
            tracking_no = EXCLUDED.tracking_no,
            warehouse_id = EXCLUDED.warehouse_id,
            warehouse_name = EXCLUDED.warehouse_name,
            shipping_provider_id = EXCLUDED.shipping_provider_id,
            shipping_provider_code = EXCLUDED.shipping_provider_code,
            shipping_provider_name = EXCLUDED.shipping_provider_name,
            shipped_time = EXCLUDED.shipped_time,
            shipped_date = EXCLUDED.shipped_date,
            dest_province = EXCLUDED.dest_province,
            dest_city = EXCLUDED.dest_city,
            gross_weight_kg = EXCLUDED.gross_weight_kg,
            cost_estimated = EXCLUDED.cost_estimated,
            source_updated_at = EXCLUDED.source_updated_at,
            calculated_at = now();
        END;
        $$;
        """
    )

    op.drop_column(TABLE_NAME, "surcharge_estimated")
    op.drop_column(TABLE_NAME, "freight_estimated")
